# -*- coding: utf-8 -*-
"""mithun_NLCEST.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DhH46IF0J0KiMITUpeLUL64qJJpiNO-t
"""

import streamlit as st
import pandas as pd
import numpy as np
import pydeck as pdk

st.set_page_config(page_title="Jal-Mithun", layout="wide")

st.title("🌊 Jal-Mithun (Hydro-Digital Twin)")
st.write("### Smart Water Decisions for Sustainable Aquifers")

with st.sidebar:
    st.header("🎛️ Control Panel")
    season = st.select_slider(
        "Select Hydrological Phase:",
        options=["Pre-Monsoon (Summer)", "Monsoon", "Post-Monsoon", "Winter"]
    )

    st.markdown("---")
    st.subheader("Scenario Controls")
    pumping = st.slider("Pumping Stress (%)", 50, 200, 100)
    recharge = st.slider("Artificial Recharge (%)", 0, 100, 10)

if "Summer" in season:
    ec_level = 1950
    wl_depth = "14.2 m bgl"
    status = "🔴 SEVERE STRESS"
    map_color = [255, 0, 0, 160]
elif "Monsoon" in season:
    ec_level = 420
    wl_depth = "2.5 m bgl"
    status = "🟢 RECHARGING"
    map_color = [0, 255, 0, 160]
else:
    ec_level = 850
    wl_depth = "7.1 m bgl"
    status = "🟡 STABLE"
    map_color = [255, 200, 0, 160]

col1, col2 = st.columns([2, 1])

with col1:
    st.subheader(f"3D Aquifer Map - {season}")
    np.random.seed(42)
    map_data = pd.DataFrame(
        np.random.randn(80, 2) / [140, 140] + [11.94, 79.81],
        columns=['lat', 'lon']
    )

    st.pydeck_chart(pdk.Deck(
        initial_view_state=pdk.ViewState(latitude=11.94, longitude=79.81, zoom=11, pitch=45),
        layers=[
            pdk.Layer(
                'HexagonLayer',
                data=map_data,
                get_position='[lon, lat]',
                radius=350,
                elevation_scale=pumping/10,
                extruded=True,
                get_fill_color=map_color,
            ),
        ],
    ))

with col2:
    st.subheader("📡 Real-Time IoT Feed")
    st.metric("Salinity (EC)", f"{ec_level} μS/cm")
    st.metric("Water Table", wl_depth)
    st.markdown("---")
    st.info(f"Status: {status}")

st.caption("Jal-Mithun | Hydro-Digital Twin for India")